[main]
font=Maple Mono:size=12

anchor=center

width=50
lines=10

horizontal-pad=24
vertical-pad=16
inner-pad=8

border-width=2
border-radius=0

icon-theme=Papirus
icons-enabled=yes

prompt="> "

fields=filename,name,generic

dpi-aware=yes
layer=overlay

[colors]
# Rose Pine
background=191724ff
text=e0def4ff
match=9ccfd8ff
selection=403d52dd
selection-text=e0def4ff
selection-match=ebbcbaff
border=26233aff
prompt=c4a7e7ff
input=e0def4ff
placeholder=908caaff
counter=908caaff
